import Head from "next/head";
import { useAuth } from "../../hooks/use-auth";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { EmployeeDashboard } from "@/components/employee-dashboard";
import { AdminDashboard } from "@/components/admin-dashboard";
import { LoginForm } from "@/components/login-form";

export default function Home() {
  const { user, logout } = useAuth();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="min-h-dvh">
        <header className="border-b">
          <div className="mx-auto max-w-4xl px-4 py-4 flex items-center justify-between">
            <h1 className="text-lg font-semibold text-foreground text-balance">
              Employee Management
            </h1>
            {user ? (
              <div className="flex items-center gap-3">
                <span className="text-sm text-muted-foreground">
                  Hi, {user.name}
                </span>
                <Button variant="outline" onClick={logout}>
                  Logout
                </Button>
              </div>
            ) : null}
          </div>
        </header>

        <section className="mx-auto max-w-4xl px-4 py-8">
          {!user ? (
            <Card>
              <CardHeader>
                <CardTitle className="text-pretty">
                  Login to track your time
                </CardTitle>
              </CardHeader>
              <CardContent>
                <LoginForm />
              </CardContent>
            </Card>
          ) : user.role === "admin" ? (
            <AdminDashboard />
          ) : (
            <EmployeeDashboard />
          )}
        </section>
      </main>
    </>
  );
}
